version: '3.4'

services:
  pwapp:
    image: ${DOCKER_REGISTRY}pwapp
    build:
      context: .
      dockerfile: PWApp/Dockerfile
    depends_on:
        - db
      
  db:
      image: mcr.microsoft.com/mssql/server:latest
      ports:
        - 1433:1433
      environment:
          SA_PASSWORD: MySupperPassword_123
          ACCEPT_EULA: Y
          MSSQL_PID: Express
